---
abstract: 'use perl *my* way'
author:
  - 'Marc Chantreux <khatar@phear.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: eirotic
requires:
  Exporter: 0
  File::Slurp: 0
  Import::Into: 0
  Method::Signatures: 0
  Perlude: 0
  YAML: 0
  base: 0
  feature: 0
  strict: 0
  warnings: 0
version: 0.0
